<?php

$html[] = "<div class='container-xl'>";
	$html[] = "<div class='response'>";
		$html[] = getMsg();
	$html[] = "</div>";
$html[] = "</div>";

$html[] = "<div class='page-header d-print-none text-white'>";
	$html[] = "<div class='container-xl'>";
		$html[] = "<div class='row g-2 '>";
			$html[] = "<div class='col'>";
				$html[] = "<div class='page-pretitle'>Account Overview</div>";
				$html[] = "<h1 class='page-title'><i class='ti ti-layout-dashboard me-2'></i> Dashboard</h1>";
			$html[] = "</div>";
			$html[] = "<div class='col-auto ms-auto d-print-none'>";
				$html[] = "<div class='btn-list text-end'>";
					
				$html[] = "</div>";
			$html[] = "</div>";
		$html[] = "</div>";
	$html[] = "</div>";
$html[] = "</div>";
$html[] = "<div class='page-body'>";
	$html[] = "<div class='container-xl'>";
		
		$html[] = "<div class='row row-deck row-cards'>";

			$html[] = "<div class='col-12'>";
				$html[] = "<div class='row row-cards'>";

					$html[] = "<div class='col-sm-6 col-lg-3'>";
						$html[] = "<div class='card card-sm'>";
							$html[] = "<div class='card-body'>";
								$html[] = "<div class='row align-items-center'>";
									$html[] = "<div class='col-auto'>";
										$html[] = "<span class='bg-primary text-white avatar'><i class='ti ti-article'></i></span>";
									$html[] = "</div>";
									$html[] = "<div class='col'>";
										$html[] = "<div class='font-weight-medium'>".$data['total_listings']." Posted Listings</div>";
										$html[] = "<div class='text-secondary'>".($data['max_post'] - $data['total_listings'])." more left</div>";
									$html[] = "</div>";
								$html[] = "</div>";
							$html[] = "</div>";
						$html[] = "</div>";
					$html[] = "</div>";

					$html[] = "<div class='col-sm-6 col-lg-3'>";
						$html[] = "<div class='card card-sm'>";
							$html[] = "<div class='card-body'>";
								$html[] = "<div class='row align-items-center'>";
									$html[] = "<div class='col-auto'>";
										$html[] = "<span class='bg-teal text-white avatar'><i class='ti ti-users'></i></span>";
									$html[] = "</div>";
									$html[] = "<div class='col'>";
										$html[] = "<div class='font-weight-medium'>".$data['this_month_leads']." Leads this month</div>";
										$html[] = "<div class='text-secondary'>Generated by MLS Website</div>";
									$html[] = "</div>";
								$html[] = "</div>";
							$html[] = "</div>";
						$html[] = "</div>";
					$html[] = "</div>";

					$html[] = "<div class='col-sm-6 col-lg-3'>";
						$html[] = "<div class='card card-sm'>";
							$html[] = "<div class='card-body'>";
								$html[] = "<div class='row align-items-center'>";
									$html[] = "<div class='col-auto'>";
										$html[] = "<span class='bg-green text-white avatar'><i class='ti ti-layers-union'></i></span>";
									$html[] = "</div>";
									$html[] = "<div class='col'>";
										$html[] = "<div class='font-weight-medium'>Active Premium</div>";
										$html[] = "<div class='text-secondary'>".$data['premium']."</div>";
									$html[] = "</div>";
								$html[] = "</div>";
							$html[] = "</div>";
						$html[] = "</div>";
					$html[] = "</div>";

					$html[] = "<div class='col-sm-6 col-lg-3'>";
						$html[] = "<div class='card card-sm'>";
							$html[] = "<div class='card-body'>";
								$html[] = "<div class='row align-items-center'>";
									$html[] = "<div class='col-auto'>";
										$html[] = "<span class='bg-red text-white avatar'><i class='ti ti-heart'></i></span>";
									$html[] = "</div>";
									$html[] = "<div class='col'>";
										$html[] = "<div class='font-weight-medium'>".$data['total_active_handshake']." Active Handshaked</div>";
										
										$html[] = "<div class='d-flex gap-3'>";

											if($data['handshake_participants']) {
												for($i=0; $i<count($data['handshake_participants']); $i++) {

													$req_fname_ini = "";
													if($data['handshake_participants'][$i]['requestor_details']['firstname']) {
														$req_fname_ini = substr($data['handshake_participants'][$i]['requestor_details']['firstname'], 0, 1);
													}

													$req_lname_ini = "";
													if($data['handshake_participants'][$i]['requestor_details']['lastname']) {
														$req_lname_ini = substr($data['handshake_participants'][$i]['requestor_details']['lastname'], 0, 1);
													}

													$req_initials = $req_fname_ini."".$req_lname_ini;

													$html[] = "<div class='avatar-list avatar-list-stacked'>";
														$html[] = "<span class='avatar avatar-xs rounded' style='background-image: url(".$data['handshake_participants'][$i]['logo'].")'>".$data['handshake_participants'][$i]['initials']."</span>";
														$html[] = "<span class='avatar avatar-xs rounded' style='background-image: url(".$data['handshake_participants'][$i]['requestor_details']['logo'].")'>$req_initials</span>";
													$html[] = "</div>";
												}
											}
										$html[] = "</div>";

									$html[] = "</div>";
								$html[] = "</div>";
							$html[] = "</div>";
						$html[] = "</div>";
					$html[] = "</div>";

				$html[] = "</div>";
			$html[] = "</div>";

			$html[] = "<div class='col-lg-4 col-md-6 col-sm-6 col-12'>";
				$html[] = "<div class='card mb-3'>";
					$html[] = "<div class='card-body'>";
						$html[] = "<h3 class='card-title'>Property Listings Traffic This Week</h3>";
						$html[] = "<div id='getTrafficChart_this_week' class='chart-sm'></div>";
					$html[] = "</div>";
				$html[] = "</div>";
			$html[] = "</div>";

			$html[] = "<div class='col-lg-4 col-md-6 col-sm-6 col-12'>";
				$html[] = "<div class='card mb-3'>";
					$html[] = "<div class='card-body'>";
						$html[] = "<h3 class='card-title'>Property Listings Traffic This Month</h3>";
						$html[] = "<div id='getTrafficChart_this_month' class='chart-sm'></div>";
					$html[] = "</div>";
				$html[] = "</div>";
			$html[] = "</div>";

			$html[] = "<div class='col-lg-4 col-md-6 col-sm-6 col-12'>";
				$html[] = "<div class='card mb-3'>";
					$html[] = "<div class='card-body'>";
						$html[] = "<h3 class='card-title'>Property Listings Traffic This Year</h3>";
						$html[] = "<div id='getTrafficChart_this_year' class='chart-sm'></div>";
					$html[] = "</div>";
				$html[] = "</div>";
			$html[] = "</div>";

			$html[] = "<div class='col-lg-4 col-md-6 col-sm-6 col-12'>";
				$html[] = "<div class='card mb-3'>";
					$html[] = "<div class='card-header'>";
						$html[] = "<h3 class='card-title'>Most Visited Property Listings</h3>";
					$html[] = "</div>";

					$html[] = "<div class='card-table table-responsive'>";
						$html[] = "<table class='table table-vcenter'>";
						$html[] = "<thead>";
							$html[] = "<th>Posting Title</th>";
							$html[] = "<th class='text-center'>Visitors</th>";
							$html[] = "<th></th>";
						$html[] = "</thead>";

						if($data['most_traffic']) {
							for($i=0; $i<count($data['most_traffic']); $i++) {
								$html[] = "<tr>";
									$html[] = "<td>".$data['most_traffic'][$i]['title']."</td>";
									$html[] = "<td class='text-center'>".$data['most_traffic'][$i]['count']."</td>";
									$html[] = "<td></td>";
								$html[] = "</tr>";
							}
						}

						$html[] = "</table>";
					$html[] = "</div>";
					
				$html[] = "</div>";

			$html[] = "</div>";

		$html[] = "</div>";


    $html[] = "</div>";
$html[] = "</div>";
    